// Code generated by SQLBoiler 4.14.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Company         string
	Education       string
	JobAnnouncement string
	User            string
	GorpMigrations  string
}{
	Company:         "Company",
	Education:       "Education",
	JobAnnouncement: "JobAnnouncement",
	User:            "User",
	GorpMigrations:  "gorp_migrations",
}
