package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.26

import (
	"context"
	"fmt"
	"github.com/Prayash07/practice_project/database/models"
	"github.com/Prayash07/practice_project/domain/user"
	graph1 "github.com/Prayash07/practice_project/graph/generated"
	"github.com/Prayash07/practice_project/graph/model"
	"github.com/volatiletech/sqlboiler/v4/boil"
)

// CreateJobAnnouncement is the resolver for the createJobAnnouncement field.
func (r *mutationResolver) CreateJobAnnouncement(ctx context.Context, input model.JobAnnouncementObject) (*model.JobAnnouncement, error) {
	panic(fmt.Errorf("not implemented: CreateJobAnnouncement - createJobAnnouncement"))
}

// CreateCompany is the resolver for the createCompany field.
func (r *mutationResolver) CreateCompany(ctx context.Context, input model.CompanyObject) (*model.Company, error) {
	panic(fmt.Errorf("not implemented: CreateCompany - createCompany"))
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input *model.UserObject) (*model.User, error) {
	user := &models.User{
		Name:    input.Name,
		Address: input.Address,
	}

	err := user.Insert(ctx, r.Db, boil.Infer())
	if err != nil {
		return nil, err
	}

	gqlUser := &model.User{
		Name:    user.Name,
		Address: user.Address,
	}

	education := &models.Education{
		DegreeName: input.DegreeName,
		Years:      input.NoOfYearsForDegree,
		UserId:     user.ID,
	}

	err2 := education.Insert(ctx, r.Db, boil.Infer())
	if err2 != nil {
		return nil, err2
	}

	return gqlUser, nil
}

// JobAnnouncements is the resolver for the jobAnnouncements field.
func (r *queryResolver) JobAnnouncements(ctx context.Context) ([]*model.JobAnnouncement, error) {
	var jobAnnouncement []*model.JobAnnouncement
	jobAnnouncement = append(jobAnnouncement, &model.JobAnnouncement{
		ID:          "1",
		Title:       "Job Announcement test",
		Description: "Job Announcement description",
		URL:         "https://www.youbube.com",
	})
	return jobAnnouncement, nil
	//panic(fmt.Errorf("not implemented: JobAnnouncements - jobAnnouncements"))
}

// Company is the resolver for the company field.
func (r *queryResolver) Company(ctx context.Context) ([]*model.Company, error) {
	panic(fmt.Errorf("not implemented: Company - company"))
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context) ([]*model.User, error) {
	users, _ := models.Users().All(context.Background(), r.Db)

	var usersData []*model.User

	for _, user := range users {
		userGql := &model.User{
			Name:    user.Name,
			Address: user.Address,
		}
		usersData = append(usersData, userGql)
	}

	return usersData, nil

}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, id string) (*model.User, error) {
	return user.FetchUserById(ctx, id, r.Db)

}

// Mutation returns graph1.MutationResolver implementation.
func (r *Resolver) Mutation() graph1.MutationResolver { return &mutationResolver{r} }

// Query returns graph1.QueryResolver implementation.
func (r *Resolver) Query() graph1.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
